representative_image.settings:
  type: config_object
  label: 'Representative Image settings'
  mapping:
    default_behavior:
      type: string
      label: 'Default behavior'
    entity_defaults:
      type: sequence
      label: 'Entity defaults'
      sequence:
        type: representative_image.entity_types
        label: 'Entity type'

representative_image.entity_types:
  type: sequence
  label: 'Entity bundles'
  sequence:
    type: representative_image.entity_bundles
    label: 'Bundle'

representative_image.entity_bundles:
  type: string
  label: 'Entity bundles'
