representative_image.settings:
  type: config_object
  label: 'Representative Image settings'
  mapping:
    default_behavior:
      type: string
      label: 'Default behavior'
    entity_defaults:
      type: sequence
      label: 'Entity defaults'
      sequence:
        type: representative_image.entity_types
        label: 'Entity type'

representative_image.entity_types:
  type: sequence
  label: 'Entity bundles'
  sequence:
    type: representative_image.entity_bundles
    label: 'Bundle'

representative_image.entity_bundles:
  type: string
  label: 'Entity bundles'

field.formatter.settings.representative_image:
  type: mapping
  label: 'Representative image'
  mapping:
    image_style:
      type: string
      label: 'Image style'
    image_link:
      type: string
      label: 'Image link'

field.field_settings.representative_image:
  type: field.field_settings.image
  label: 'Representative Image settings'
  mapping:
    representative_image_field_name:
      type: string
      label: 'Representative image field name'
    representative_image_behavior:
      type: string
      label: 'Representative image behavior'

field.storage_settings.representative_image:
  type: field.storage_settings.image
  label: 'Representative image settings'

field.widget.settings.representative_image:
  type: field.widget.settings.image_image
  label: 'Image field display format settings'
